export const weatherMapping: Record<number, { label: string; icon: string }> = {
    0: { label: "Clear Sky", icon: "clear-day" },
    1: { label: "Mainly Clear", icon: "clear-day" },
    2: { label: "Partly Cloudy", icon: "partly-cloudy" },
    3: { label: "Overcast", icon: "overcast" },
    45: { label: "Foggy", icon: "fog" },
    48: { label: "Rime Fog", icon: "fog" },
    51: { label: "Light Drizzle", icon: "drizzle" },
    53: { label: "Drizzle", icon: "drizzle" },
    55: { label: "Heavy Drizzle", icon: "drizzle" },
    61: { label: "Light Rain", icon: "rain" },
    63: { label: "Rain", icon: "rain" },
    65: { label: "Heavy Rain", icon: "rain" },
    71: { label: "Light Snow", icon: "hail" },
    73: { label: "Snow", icon: "hail" },
    75: { label: "Heavy Snow", icon: "hail" },
    77: { label: "Snow Grains", icon: "hail" },
    80: { label: "Light Showers", icon: "rain" },
    81: { label: "Rain Showers", icon: "rain" },
    82: { label: "Violent Showers", icon: "rain" },
    85: { label: "Snow Showers", icon: "hail" },
    86: { label: "Heavy Snow Showers", icon: "hail" },
    95: { label: "Thunderstorm", icon: "thunderstorms" },
    96: { label: "Thunderstorm & Hail", icon: "thunderstorms" },
    99: { label: "Thunderstorm & Heavy Hail", icon: "thunderstorms" },
};
